### ISSUE TITLE
Feature request: update for latest version of LUFA.

### ISSUE THREAD

**Issue by trusktr** [harlequin-tech/arduino-usb#1]
Feature request: update this to work with the most recent version of [LUFA](https://github.com/abcminiuser/lufa).

**Comment by EdSalisbury** [comment]
Seconded - I'm trying to modify the code to work with it, and running into lots of issues.

**Comment by harlequin-tech** [comment]
If you get the new LUFA working, please send a pull-up request and I'll add it to the repo here.
