### ISSUE TITLE
Feature request: USB MassStorage.

### ISSUE THREAD

**Issue by trusktr** [harlequin-tech/arduino-usb#2]
A USB MassStorage firmware. There's a stub in the latest [LUFA](https://github.com/abcminiuser/lufa) demos, it just needs to be made to work with Arduino. I don't know enough to do it yet.

**Comment by q2dg** [comment]
+1!!

**Comment by NicoHood** [comment]
It'd be better if you code this stuff yourself and learn USB. Better code with LUFA only and understand the code. This is nothing what you want to run on Arduino environments with an unrelyable Serial bridge. Grab a 32u4 and code your own Lufa project.
