### ISSUE TITLE
Trouble on mega 2560 volume up, volume down...

### ISSUE THREAD

**Issue by blacktxandy** [harlequin-tech/arduino-usb#4]
Im having some problems trying to send volume up and volume down using the demo code on arduino mega 2560 R3... all the alphanumeric chars can be read by the host (PC running windows 10), but the multimedia keys cannot be read.
I wrote a small code to send all keypresses at intervals of 500ms, it starts sending buf[2]=0 and goes up to 255... always sending a buf[2]=0 to make the release of the keys.
I've uploaded the keyboard firmware onto my 16u2 ic on the mega board using dfu and flip.
I dont know what is wrong :/
can anyone help me?

**Comment by NicoHood** [comment]
Take a look at this, its much easier:
https://github.com/NicoHood/HoodLoader2
https://github.com/NicoHood/HID
